# Language configs

[[language]]
name = "lua"
scope = "source.lua"
file-types = ["lua"]
shebangs = ["lua"]
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
comment-token = "--"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "lua-language-server", args = [] }
