# vim:set ft=tmux:
# This tmux statusbar config was created by tmuxline.vim
# on Sat, 16 May 2020

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"

# Messages
set -g message-command-style "fg=#5C6773,bg=#F0F0F0"
set -g message-style "fg=#5C6773,bg=#F0F0F0"

# Core UI
set -g status-right-style "none"
set -g pane-active-border-style "fg=#55B4D4"
set -g pane-border-style "fg=#E6E6E6"
set -g status-style "none,bg=#FAFAFA"

set -g status-right-length "100"
set -g status-left-length "100"

setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#5C6773,bg=#FAFAFA"

# Left segment — session name
set -g status-left "#[fg=#FFFFFF,bg=#55B4D4] #S #[fg=#55B4D4,bg=#FAFAFA,nobold,nounderscore,noitalics]"

# Right segment — date, time, host
set -g status-right "#[fg=#E6E6E6,bg=#FAFAFA,nobold,nounderscore,noitalics]#[fg=#5C6773,bg=#F0F0F0] %Y-%m-%d  %H:%M #[fg=#55B4D4,bg=#F0F0F0,nobold,nounderscore,noitalics]#[fg=#FFFFFF,bg=#55B4D4] #h "

# Window list (inactive)
setw -g window-status-format "#[fg=#5C6773,bg=#FAFAFA] #I #[fg=#5C6773,bg=#FAFAFA] #W "

# Current window
setw -g window-status-current-format "#[fg=#FAFAFA,bg=#F0F0F0,nobold,nounderscore,noitalics]#[fg=#5C6773,bg=#F0F0F0] #I #[fg=#5C6773,bg=#F0F0F0] #W #[fg=#F0F0F0,bg=#FAFAFA,nobold,nounderscore,noitalics]"

