# vim:set ft=tmux:
# Catppuccin Latte

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"

set -g message-command-style "fg=#4C4F69,bg=#E6E9EF"
set -g message-style         "fg=#4C4F69,bg=#E6E9EF"

set -g status-style "none,bg=#EFF1F5"
set -g status-right-style "none"

set -g pane-active-border-style "fg=#1E66F5"
set -g pane-border-style        "fg=#DCE0E8"

set -g status-right-length "100"
set -g status-left-length  "100"

setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#4C4F69,bg=#EFF1F5"

set -g status-left  "#[fg=#FFFFFF,bg=#1E66F5] #S #[fg=#1E66F5,bg=#EFF1F5,nobold,nounderscore,noitalics]"

set -g status-right "#[fg=#DCE0E8,bg=#EFF1F5,nobold,nounderscore,noitalics]#[fg=#4C4F69,bg=#DCE0E8] %Y-%m-%d  %H:%M #[fg=#1E66F5,bg=#E6E9EF,nobold,nounderscore,noitalics]#[fg=#FFFFFF,bg=#1E66F5] #h "

# set -g status-right "#[fg=#DCE0E8,bg=#EFF1F5,nobold,nounderscore,noitalics]#[fg=#4C4F69,bg=#E6E9EF] %Y-%m-%d  %H:%M #[fg=#1E66F5,bg=#E6E9EF,nobold,nounderscore,noitalics]#[fg=#FFFFFF,bg=#1E66F5] #h "

setw -g window-status-format "#[fg=#4C4F69,bg=#EFF1F5] #I #[fg=#4C4F69,bg=#EFF1F5] #W "

setw -g window-status-current-format "#[fg=#EFF1F5,bg=#E6E9EF,nobold,nounderscore,noitalics]#[fg=#4C4F69,bg=#E6E9EF] #I #[fg=#4C4F69,bg=#E6E9EF] #W #[fg=#E6E9EF,bg=#EFF1F5,nobold,nounderscore,noitalics]"

