# vim:set ft=tmux:
# Catppuccin Frappe

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"

set -g message-command-style "fg=#C6D0F5,bg=#414559"
set -g message-style         "fg=#C6D0F5,bg=#414559"

set -g status-style "none,bg=#303446"
set -g status-right-style "none"

set -g pane-active-border-style "fg=#8CAAEE"
set -g pane-border-style        "fg=#292C3C"

set -g status-right-length "100"
set -g status-left-length  "100"

setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#8CAAEE,bg=#303446"

set -g status-left  "#[fg=#303446,bg=#8CAAEE] #S #[fg=#8CAAEE,bg=#303446,nobold,nounderscore,noitalics]"

set -g status-right "#[fg=#414559,bg=#303446,nobold,nounderscore,noitalics]#[fg=#C6D0F5,bg=#414559] %Y-%m-%d  %H:%M #[fg=#8CAAEE,bg=#414559,nobold,nounderscore,noitalics]#[fg=#303446,bg=#8CAAEE] #h "

setw -g window-status-format "#[fg=#8CAAEE,bg=#303446] #I #[fg=#8CAAEE,bg=#303446] #W "

setw -g window-status-current-format "#[fg=#303446,bg=#414559,nobold,nounderscore,noitalics]#[fg=#C6D0F5,bg=#414559] #I #[fg=#C6D0F5,bg=#414559] #W #[fg=#414559,bg=#303446,nobold,nounderscore,noitalics]"

