# vim:set ft=tmux:
# This tmux statusbar config was created by tmuxline.vim
# on Fri, 05 Jun 2020

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=#232526,bg=#f8f8f0"
set -g status-right-style "none"
set -g pane-active-border-style "fg=#b58900"
set -g status-style "none,bg=#e6e6e6"
set -g message-style "fg=#232526,bg=#f8f8f0"
set -g pane-border-style "fg=#cccccc"
set -g status-right-length "100"
set -g status-left-length "100"

setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#232526,bg=#e6e6e6"

set -g status-left "#[fg=#ffffff,bg=#b58900] #S #[fg=#b58900,bg=#e6e6e6,nobold,nounderscore,noitalics]"

set -g status-right "#[fg=#cccccc,bg=#e6e6e6,nobold,nounderscore,noitalics]#[fg=#232526,bg=#f8f8f0] %Y-%m-%d  %H:%M #[fg=#b58900,bg=#f8f8f0,nobold,nounderscore,noitalics]#[fg=#ffffff,bg=#b58900] #h "

setw -g window-status-format "#[fg=#232526,bg=#e6e6e6] #I #[fg=#232526,bg=#e6e6e6] #W "
setw -g window-status-current-format "#[fg=#e6e6e6,bg=#f8f8f0,nobold,nounderscore,noitalics]#[fg=#232526,bg=#f8f8f0] #I #[fg=#232526,bg=#f8f8f0] #W #[fg=#f8f8f0,bg=#e6e6e6,nobold,nounderscore,noitalics]"

