#!/usr/bin/env bash
# Name: dotfiles installer
# Author: Kuntau
# Last edit: 1/12/2025

set -eu

# --- Configuration ---
SCRIPT_NAME="$(basename "$0")"
VERSION="1.0.0"
DEBUG=false
VERBOSE=false
ALL=false
MAKE_BACKUP=true
OS=$(uname)
HOSTNAME=$(hostname)
DOTFILES=$HOME/dotfiles
THEME_DIR=$DOTFILES/zsh/themes
XDG_CONFIG_HOME=$HOME/.config
CHOME=$XDG_CONFIG_HOME
ZHOME=$HOME/.znap
FZF_HOME=$HOME/.fzf

BOLD='\033[1m'
UNDERLINE='\033[4m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

ICON_WAIT='⏳'
ICON_OK='✅'
ICON_ERR='❌'
ICON_WARN='⚠️'
ICON_ASK='❔'
ICON_GITHUB=' '

# Config files to install
CONFIG_FILES=(
  editorconfig
  gitconfig
  gitignore
  npmrc
  ripgreprc
  tmux.conf
  vimrc
  zshrc
)

CONFIG_DIRS=(
  atuin
  bat
  delta
  gitui
  helix
  kitty
  lazyvim
  mpv
  neovide
  nu
  nvim
  wezterm
)

REQUIRED_BIN=(
  zsh
  git
  bash
  curl
)

CORE_BIN=(
  rg
  fd
  uv
  fzf
  nnn
  bat
  nvim
  mosh
  tmux
  rsync
  atuin
  delta
  vivid
  zoxide
)

EXTRA_BIN=(
  sd
  nu
  hx
  jj
  vim
  bfs
  dua
  dust
  glow
  gitui
  aria2c
  rclone
  fdupes
  fclones
  lazygit
)


# prompt with default to *yes* borrowed from *fzf*
# return code 0 for true, 1-255 for false
ask() {
  if [[ $ALL = true ]]; then return 0; fi
  echo ""
  while true; do
    read -p "$1 ([y]/n) " -r
    REPLY=${REPLY:-"y"}
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      return 0
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
      return 1
    fi
  done
}


# Symlink file/folder: $1=SOURCE/ORIGIN $2=TARGET/NEW
make_link() {
  local cmd_prefix=${DEBUG:+"echo"}
  local source_path=$1
  local sym_path=$2
  local base_file_name
  base_file_name=$(basename "$sym_path")

  # check if link exist, make backup & make symbolic link
  if [[ -e $sym_path && $MAKE_BACKUP = true ]]; then
    echo -e "$ICON_WARN ${BOLD}${YELLOW}$base_file_name${NC} exists.. The original file will be backup to ${BOLD}${YELLOW}$base_file_name.bak${NC}"
    $cmd_prefix mv "$sym_path" "$sym_path.bak"
  fi
  echo -e "$ICON_OK ${BOLD}${GREEN}$base_file_name${NC} linked to ${BOLD}${GREEN}${source_path/#$HOME/\~}${NC}"
  $cmd_prefix ln -sf "$source_path" "$sym_path"
}


# Create directory: $1=DIR_PATH
make_dir() {
  local cmd_prefix=${DEBUG:+"echo"}
  local dir=$1
  if [[ -d $dir ]]; then
    echo -e "$ICON_WARN ${BOLD}${YELLOW}${dir/#$HOME/\~}${NC} exist, skip making directory..."
  else
    echo -e "$ICON_OK Creating directory ${BOLD}${GREEN}${dir/#$HOME/\~}${NC}..."
    $cmd_prefix mkdir -p "$dir"
  fi
}


# setup configs in XDG_CONFIG_HOME
setup_configs() {
  local cmd_prefix=${DEBUG:+"echo"}
  local dir=$1
  make_dir "$CHOME/$dir"
  for file in "$DOTFILES/config/$dir"/*; do
    local base_file
    base_file=$(basename "$file")
    make_link "$file" "$CHOME/$dir/$base_file"
  done
  echo ""
}


# $1=BINARY $2=TEXT_OK $3=TEXT_ERR
exist() {
  local bin=$1
  local success=${2:-"$ICON_OK OK ${BOLD}${GREEN}$bin${NC} available."}
  local error=${3:-"$ICON_ERR ERR ${BOLD}${RED}$bin${NC} can't be found in \$PATH."}
  if command -v "$bin" >/dev/null 2>&1; then
    echo -e "$success"
    return 0
  else
    echo -e "$error"
    return 1
  fi
}


# Install homebrew
install_homebrew() {
  if ! exist "brew"; then
    if ask "$ICON_ASK Do you want to install homebrew? "; then
      $(which bash) -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
  fi
}


# TODO: Make automatic install without using the installer
# Install MacPorts
install_macports() {
  if ! exist "port"; then
    if ask "$ICON_ASK Do you want to install MacPorts? "; then
      xcode-select --install
      xcodebuild -license
      echo -e "It's complicated. For now install MacPorts from ${BOLD}https://guide.macports.org/chunked/installing.macports.html${NC}"
    fi
  fi
}


# Check package manager
check_pacman() {
  # $(which bash) -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo ""
  echo "$ICON_WAIT Checking package manager..."
  if [[ $OS = Linux ]]; then
    install_homebrew
  elif [[ $OS = Darwin ]]; then
    install_homebrew
    install_macports
  fi
  return 0
}


# check array of binary. $1=GROUP $2=ARRAY_OF_BIN
check_binary() {
  local -n misses=$1
  shift
  local bins=("$@")
  for bin in "${bins[@]}"; do
    if ! exist "$bin"; then
      misses+=("$bin")
    fi
  done
}


# Clone repo: $1=NAME $2=URL $3=DIR
clone_repo() {
  local cmd_prefix=${DEBUG:+"echo"}
  local name=$1
  local url=$2
  local dir=$3
  if [[ -d $dir ]]; then
    echo -e "$ICON_WARN You already have ${BOLD}${YELLOW}$name${NC} installed, skipping..."
  else
    echo -e "$ICON_GITHUB Cloning ${BOLD}${GREEN}$name${NC}..."
    $cmd_prefix "$(which git)" clone --filter=blob:none "$url" "$dir"
  fi
}


# START INSTALL #
main() {
  local missings=()
  echo "$ICON_WAIT Checking requirements..."
  for tool in "${REQUIRED_BIN[@]}"; do
    if ! exist "$tool"; then
      return 1
    fi
  done

  check_pacman

  # check core tools
  if ask "$ICON_ASK Check core tool availability? "; then
    echo "$ICON_WAIT Checking core tool availability..."
    echo ""
    check_binary missings "${CORE_BIN[@]}"
    echo "${missings[*]}"
  fi

  # check extra tools
  if ask "$ICON_ASK Check extra tool availability? "; then
    echo "$ICON_WAIT Checking extra tool availability..."
    echo ""
    check_binary "${EXTRA_BIN[@]}"
    echo "${missings[*]}"
  fi

  if ! ask "$ICON_ASK Continue installation? "; then exit; fi

  # Link config files
  if ask "$ICON_ASK Link config files? "; then
    echo "$ICON_WAIT Linking config files..."
    echo ""
    for dir in "${CONFIG_FILES[@]}"; do
      make_link "$DOTFILES/config/$dir" "$HOME/.$dir"
    done
    # Link ssh config
    make_link "$DOTFILES/config/ssh-config" "$HOME/.ssh/config"
  fi

  # Link config directories
  if ask "$ICON_ASK Link config directories? "; then
    echo "$ICON_WAIT Linking config directories..."
    echo ""
    for dir in "${CONFIG_DIRS[@]}"; do
      setup_configs "$dir"
    done
  fi

  # Install fzf
  if ask "$ICON_ASK Install fzf? "; then
    clone_repo "fzf" "https://github.com/junegunn/fzf.git" "$FZF_HOME"
  fi

  # Install znap
  if ask "$ICON_ASK Install znap? "; then
    clone_repo "znap" "https://github.com/merlonrichert/zsh-snap.git" "$ZHOME/zsh-snap"
  fi

  # Install tmux plugins manager
  if ask "$ICON_ASK Install TMUX Plugin Manager (TPM)? "; then
    clone_repo "tpm" "https://github.com/tmux-plugins/tpm.git " "$HOME/.tmux/plugins/tpm"
  fi

  if ! ask "$ICON_ASK Continue installation? "; then exit; fi

  # check .secret file availability
  echo ""
  echo "$ICON_WAIT Checking .secret file..."
  if [[ -f $HOME/.secret ]]; then
    echo "$ICON_WARN .secret file exist.. Skip installing"
  else
    touch "$HOME/.secret"
  fi

  # append path.. possible duplicate..
  if ask "$ICON_ASK Append \$PATH to the end of ~/.zshrc? "; then
    export PATH=\$PATH:$PATH >> "$HOME/.zshrc"
  fi

  if ask "$ICON_ASK Change default shell to zsh? "; then
    chsh -s "$(which zsh)"
  fi

  echo ""
  echo "$ICON_ASK Select powerlevel10k theme"
  select opt in basic powerline nerdfont skip; do
    case $opt in
      basic)
        make_link "$THEME_DIR/p10k.basic.zsh" "$HOME/.p10k.zsh"
        break;;
      powerline)
        make_link "$THEME_DIR/p10k.powerline.zsh" "$HOME/.p10k.zsh"
        break;;
      nerdfont)
        make_link "$THEME_DIR/p10k.nerdfont.zsh" "$HOME/.p10k.zsh"
        break;;
      skip)
        echo "Skip linking p10k theme"
        break;;
      *)
        echo "Invalid option $opt"
        ;;
    esac
  done
  echo ""

  # source ~/.zshrc
  # $EDITOR +PlugInstall

  hash node 2>/dev/null || { echo "No NodeJS installation detected. Alternative https://github.com/nodesource/distributions/blob/master/README.md"; }
  hash nginx 2>/dev/null || { echo "No nginx installation detected. "; }

  echo "$ICON_OK dotfiles install completed."

}


show_help() {
    cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS] [ARGS...]

Options:
      --help      Show this help message and exit

  -h, --help      Show this help message and exit
  -v, --version   Show version number and exit
      --debug     Enabe debug mode
EOF
    exit 0
}


show_version() {
    echo "$SCRIPT_NAME $VERSION"
    exit 0
}


while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_help
            ;;
        -v|--version)
            show_version
            ;;
        --no-backup)
            MAKE_BACKUP=false
            ;;
        --verbose)
            VERBOSE=true
            ;;
        --all)
            ALL=true
            ;;
        --debug)
            DEBUG=true
            ;;
        --)  # End of options
            shift
            break
            ;;
        -*|*)
            echo "Error: Unknown option: $1" >&2
            echo "Try '$SCRIPT_NAME --help' for usage." >&2
            exit 1
            ;;
    esac
    shift
done


# Call main with arguments "$@"
main "$@"
