# vim: ft=zsh foldmethod=marker foldlevel=1 nomodeline:

if [[ -n "$ZSH_DEBUGRC" ]]; then
  zmodload zsh/zprof
fi

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# start zplug {{{
source ~/.zplug/init.zsh

# zplug can manage itself
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# from oh-my-zsh
zplug 'lib/clipboard',          from:oh-my-zsh
zplug 'lib/history',            from:oh-my-zsh
# zplug 'lib/completion',         from:oh-my-zsh
zplug 'lib/key-bindings',       from:oh-my-zsh
zplug 'lib/directories',        from:oh-my-zsh
zplug 'plugins/brew',           from:oh-my-zsh
zplug 'plugins/bun',            from:oh-my-zsh
zplug 'plugins/copybuffer',     from:oh-my-zsh
zplug 'plugins/copyfile',       from:oh-my-zsh
zplug 'plugins/copypath',       from:oh-my-zsh
zplug 'plugins/cp',             from:oh-my-zsh
zplug 'plugins/docker',         from:oh-my-zsh
zplug 'plugins/docker-compose', from:oh-my-zsh
zplug 'plugins/git',            from:oh-my-zsh
zplug 'plugins/git-extras',     from:oh-my-zsh
zplug 'plugins/git-flow',       from:oh-my-zsh
zplug 'plugins/mosh',           from:oh-my-zsh
zplug 'plugins/nmap',           from:oh-my-zsh
zplug 'plugins/safe-paste',     from:oh-my-zsh
zplug 'plugins/ssh',            from:oh-my-zsh
zplug 'plugins/sudo',           from:oh-my-zsh
zplug 'plugins/taskwarrior',    from:oh-my-zsh
zplug 'plugins/tmux',           from:oh-my-zsh

# local/dotfiles
zplug "~/dotfiles/zsh/completions", from:local

# from github
zplug "zsh-users/zsh-completions", depth:1
zplug "bigH/git-fuzzy", depth:1, as:command, use:"bin/git-fuzzy"
zplug "jeffreytse/zsh-vi-mode", depth:1
zplug "zsh-users/zsh-autosuggestions", depth:1
zplug "b4b4r07/enhancd", depth:1, use:init.sh
zplug "agkozak/zsh-z", depth:1
zplug "le0me55i/zsh-extract", depth:1
zplug "marlonrichert/zsh-edit", depth:1
zplug "zsh-users/zsh-history-substring-search", as:plugin, depth:1, defer:1
zplug "marlonrichert/zsh-autocomplete", depth:1, defer:2
zplug "z-shell/F-Sy-H", depth:1, defer:3

# theme
zplug "romkatv/powerlevel10k", depth:1, use:powerlevel10k.zsh-theme

if ! zplug check; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load
# }}}

# Set ENV VARIABLE {{{
OS_NAME=$(uname)
HOST_NAME=$(hostname)
DOTFILES=$HOME/dotfiles

exists() { command -v "$1" >/dev/null 2>&1; }
is_day() { [ $(date +%H) -ge 8 ] && [ $(date +%H) -le 19 ] }

# OS specific ENVIRONMENT VARIABLE
if [[ $OS_NAME == Linux ]]; then
  # export PATH=~/npm/bin:/usr/local/go/bin:$PATH
  # export PATH=~/.local/bin:$PATH
  # rust
  # golang
  export PATH=$PATH:/usr/local/go/bin
  export DENO_INSTALL='/home/kuntau/.deno'

  # nnn
  export NNN_OPENER='nuke'

  # machine specific ENVIRONMENT VARIABLE
  if [[ $HOST_NAME == 'hqsvr' ]]; then
    export COMPOSER_HOME=$HOME/.composer

    # atuin - https://atuin.sh
    source $HOME/.atuin/bin/env

    export NNN_BMS='d:~/dotfiles;D:/DL/Downloads;v:/HQPOOL/Videos;c:/HQPOOL/Coding;T:/HQPOOL/DATA;P:/HQPOOL;C:~/.config/;L:~/.local;f:/HQPOOL/Coding/forks'
  fi
elif [[ $OS_NAME == Darwin ]]; then
  # python: https://docs.python.org/3/using/cmdline.html#environment-variables
  export PYTHONUSERBASE=~/.local
  export PATH=$PATH:$HOME/Library/Python/3.9/bin

  # GPG. Read https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key
  GPG_TTY=$(tty)
  export GPG_TTY

  # Homebrew
  export HOMEBREW_CASK_OPTS="--appdir=~/Applications"
  export HOMEBREW_NO_AUTO_UPDATE=0
  export HOMEBREW_NO_INSTALL_CLEANUP=0
  export HOMEBREW_AUTO_UPDATE_SECS=86400

  # nnn
  export NNN_OPENER='open' # set MacOS nnn opener

  # Add MacPorts MAN path
  export MANPATH=$MANPATH:/opt/local/man

  # LSP
  export PATH=~/.local/share/nvim/mason/bin:$PATH # Mason LSP bin dir

  # machine specific ENVIRONMENT VARIABLE
  if [[ $HOST_NAME == 'HQ' ]]; then
    export ANDROID_HOME=/Volumes/HOME/Android/SDK
    export PATH=$PATH:/Volumes/HOME/Android/flutter/bin
    export NNN_BMS='D:~/dotfiles;d:/Volumes/HOME/Downloads;E:/Volumes/Entertainment;f:~/coding/forks;c:~/coding;C:~/.config;L:~/.local'
  elif [[ $HOST_NAME == 'rMBP' ]]; then
    export ANDROID_HOME=~/Library/Android/sdk
    export NNN_BMS='D:~/dotfiles;d:~/downloads;f:~/coding/forks;c:~/coding;C:~/.config;L:~/.local;V:/Volumes'
  fi
elif [[ $OS_NAME == CYGWIN_NT-6.1 ]]; then
  export PATH=/usr/local/bin:/usr/bin:/cygdrive/c/"Program Files (x86)/NVIDIA Corporation"/PhysX/Common:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/"Program Files/Intel/DMIX":$PATH
  source ~/dotfiles/mintty/sol.dark
fi

# Add MAN path
export MANPATH=$MANPATH:$ZPLUG_HOME/doc/man

# Fix locale
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
# }}}

# Plugins config & ENV {{{
# zsh-completions. https://github.com/zsh-users/zsh-completions/
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240"   # fg=#707a8c,bg=cyan,bold,underline"

# zsh-autcomplete configs https://github.com/marlonrichert/zsh-autocomplete/blob/main/.zshrc
# Some snippets from https://github.com/tshu-w/dotfiles/blob/f06c7c7f7084e615c82d4d56efb008b39bdb24cd/config/zsh/.zshrc#L33-L48
# zstyle '*:compinit' arguments -D -i -u -C -w # might cause `compinit` not generating `zcompdump`
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}     # use with `vivid`
zstyle ':completion:*' file-sort date
zstyle ':completion:*:*' matcher-list 'm:{[:lower:]-}={[:upper:]_}' '+r:|[.]=**'
zstyle ':completion:*:paths' path-completion yes
# zstyle ':autocomplete:*' ignored-input '..##'
zstyle ':autocomplete:*' add-space executables aliases functions builtins reserved-words commands
zstyle ':autocomplete:*' min-delay 0.3  # seconds (float)
zstyle ':autocomplete:*' min-input 2  # characters (int)
zstyle ':autocomplete:*' insert-unambiguous yes
zstyle ':autocomplete:*' fzf-completion yes
# zstyle ':autocomplete:*' default-context history-incremental-search-backward
bindkey -M menuselect "^[m" accept-and-hold
bindkey -M menuselect "^M" .accept-line


# nnn - https://github.com/jarun/nnn
NNN_PLUG_FZF='c:fzcd;o:fzopen;j:autojump;h:fzhist;p:fzplug;g:gitroot'
NNN_PLUG_REST='3:mp3conv;4:ipinfo;v:preview-tui;s:chksum;x:!chmod +x "$nnn";m:-!|mediainfo "$nnn";k:pskill;i:imgview;l:launch'
NNN_PLUG="$NNN_PLUG_FZF;$NNN_PLUG_REST"
export NNN_PLUG
export NNN_OPTS='acEFrxQU'
BLK="04" CHR="04" DIR="04" EXE="00" REG="00" HARDLINK="00" SYMLINK="06" MISSING="00" ORPHAN="01" FIFO="0F" SOCK="0F" OTHER="02"
export NNN_COLORS='a321e2be;1234'
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
# export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_TRASH=0

# bat - https://github.com/sharkdp/bat
export BAT_THEME="gruvbox-dark"
export BAT_STYLE="plain"
export BAT_PAGER="less -RS"

# enhancd - https://github.com/b4b4r07/enhancd
export ENHANCD_FILTER=fzf
export ENHANCD_DISABLE_DOT=0
export ENHANCD_DISABLE_HYPHEN=0
export ENHANCD_HYPHEN_ARG=';'
export ENHANCD_DOT_ARG='.'

# ripgrep - https://github.com/BurntSushi/ripgrep
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

# NOTE: Need more research
# zsh-vi-mode - https://github.com/jeffreytse/zsh-vi-mode
# export ZVM_INIT_MODE=sourcing
# export ZVM_CURSOR_STYLE_ENABLED=true

# FIX the blinding green on green directory listing on external drive.
# Read more https://unix.stackexchange.com/questions/94498/what-causes-this-green-background-in-ls-output
if [[ -f ~/.dircolors ]]; then
  eval $(dircolors -b ~/.dircolors)
elif [[ -f /etc/DIR_COLORS ]]; then
  eval $(dircolors -b /etc/DIR_COLORS)
fi
# }}}

# Update $PATH (platform *nix)) {{{
exists npm      && export NPM_CONFIG_PREFIX=$HOME/.npm-global   # npm -g install location
exists npm      && export PATH=$HOME/.npm-global/bin:$PATH      # npm global binary path
exists pnpm     && export PNPM_HOME=$HOME/.npm-global/bin       # pnpm global binary path
exists pip      && export PATH=$HOME/.local/bin:$PATH           # pip app binary path
exists cargo    && export PATH=$HOME/.cargo/bin:$PATH           # rust cargo binary path
exists composer && export PATH=$HOME/.composer/vendor/bin:$PATH # composer global binary path
exists snap     && export PATH=/snap/bin:$PATH                  # snap binary path
export PATH=$PATH:$DENO_INSTALL/bin                             # deno binary path
export PATH=$PATH:/usr/local/sbin                               # some brew installed in `sbin`
export PATH=$DOTFILES/bin:$PATH
# }}}

# Extra sources {{{
# zsh-vi-mode messed with key-bindings. So need to set ours after `zvm` init
function zvm_after_init() {
  bindkey              '^I' menu-complete
  bindkey "$terminfo[kcbt]" reverse-menu-complete
  bindkey              '^I' menu-select
  bindkey "$terminfo[kcbt]" menu-select
  bindkey -M menuselect              '^I'         menu-complete
  bindkey -M menuselect "$terminfo[kcbt]" reverse-menu-complete

  [[ -x rustup ]] && source $HOME/.cargo/env
  [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
  exists fzf && source $DOTFILES/zsh/fzf.zsh
  exists atuin && eval "$(atuin init zsh)" # atuin - sync, search & backup shell history
  exists nnn && source $DOTFILES/nnn/quitcd.zsh

  # Customs
  bindkey -M viins '^Xa' _expand_alias
  bindkey -M viins '^R' atuin-search-viins
  bindkey -M vicmd '' up-line-or-history
  bindkey -M vicmd '' down-line-or-history

  # zsh-history-substring-search configuration
  bindkey '^[[A' history-substring-search-up   # or '\eOA' = Up arrow
  bindkey '^[[B' history-substring-search-down # or '\eOB' = Down arrow
  export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1

  source $DOTFILES/zsh/default.zsh # my defaults
  source $DOTFILES/zsh/aliases.zsh # my aliases
  source $HOME/.secret             # don't commit this file
  typeset -U PATH                  # remove dups from $PATH
  typeset -U MANPATH               # remove dups from $MANPATH
}

[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

if [[ -n "$ZSH_DEBUGRC" ]]; then
  zprof
fi
# }}}
