# vim: foldmethod=marker foldlevel=0 nomodeline:

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# start zplug {{{
source ~/.zplug/init.zsh

# from oh-my-zsh
zplug "lib/clipboard",          depth:1, from:oh-my-zsh
zplug "lib/history",            from:oh-my-zsh
zplug "lib/completion",         from:oh-my-zsh
zplug "lib/key-bindings",       from:oh-my-zsh
zplug "lib/directories",        from:oh-my-zsh
zplug "plugins/vi-mode",        from:oh-my-zsh
zplug "plugins/brew",           from:oh-my-zsh
zplug "plugins/git",            from:oh-my-zsh
zplug "plugins/git-extras",     from:oh-my-zsh
zplug "plugins/git-flow",       from:oh-my-zsh
zplug "plugins/node",           from:oh-my-zsh
zplug "plugins/npm",            from:oh-my-zsh
zplug "plugins/tmux",           from:oh-my-zsh
zplug "plugins/docker",         from:oh-my-zsh
zplug "plugins/docker-compose", from:oh-my-zsh

# from github
zplug "zsh-users/zsh-completions", depth:1
zplug "zsh-users/zsh-autosuggestions", depth:1
zplug "zsh-users/zsh-history-substring-search", depth:1
zplug "zsh-users/zsh-syntax-highlighting", depth:1, defer:2
zplug "b4b4r07/enhancd", depth:1, use:init.sh
zplug "agkozak/zsh-z", depth:1
zplug "Vifon/zranger", depth:1
# zplug "rupa/z", use:z.sh
# zplug "clvv/fasd", use:fasd

# theme
zplug "romkatv/powerlevel10k", depth:1, use:powerlevel10k.zsh-theme

if ! zplug check; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load
# }}}

# Set ENV VARIABLE {{{
OS_NAME=$(uname)
HOST_NAME=$(hostname)
DOTFILES_HOME=$HOME/dotfiles

# OS specific ENVIRONMENT VARIABLE
if [[ $OS_NAME == Linux ]]; then
  # export PATH=~/npm/bin:/usr/local/go/bin:$PATH
  # export PATH=~/.local/bin:$PATH
  export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
  export DENO_INSTALL='/home/kuntau/.deno'
  export PATH=$PATH:~/.local/lsp/sumneko.lua-2.5.3/server/bin/Linux # Sumneko lua path
elif [[ $OS_NAME == Darwin ]]; then
  # export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH

  # set android dev path
  if [[ $HOST_NAME == 'HQ' ]]; then
    export ANDROID_HOME=/Volumes/HOME/Android/SDK
    export PATH=$PATH:/Volumes/HOME/Android/flutter/bin
  elif [[ $HOST_NAME == 'rMBP' ]]; then
    export ANDROID_HOME=~/Library/Android/sdk
  fi

  # pip
  export PATH=$PATH:$HOME/Library/Python/3.9/bin

  # rust
  # golang
  # export GOROOT='/usr/local/Cellar/go/1.1.2'

  # Ruby
  # RUBYROOT='/usr/local/Cellar/ruby/2.1.1_1'
  # USE RUBY GEM AS USER --user-install
  # GEM_HOME=$HOME/.gem/ruby/2.6.0/
  # export PATH=$PATH:$HOME/.gem/ruby/2.6.0/bin
  # GEMPATH='~/.gem/ruby/2.1.0'
  # export PATH=$PATH:$RUBYROOT/bin:$GEMPATH

  # Homebrew
  export HOMEBREW_CASK_OPTS="--appdir=~/Applications"
  export HOMEBREW_NO_AUTO_UPDATE=0
  export HOMEBREW_AUTO_UPDATE_SECS=86400

  # One off binary
  export PATH=~/.local/lsp/sumneko.lua-2.5.3/server/bin/macOS:$PATH # Sumneko lua path
  export PATH=~/Applications/goneovim.app/Contents/MacOS:$PATH      # Neovim GUI in Go
  export PATH=/usr/local/opt/sqlite/bin:$PATH                       # Homebrew's sqlite3
elif [[ $OS_NAME == CYGWIN_NT-6.1 ]]; then
  export PATH=/usr/local/bin:/usr/bin:/cygdrive/c/"Program Files (x86)/NVIDIA Corporation"/PhysX/Common:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/"Program Files/Intel/DMIX":$PATH
  source ~/dotfiles/mintty/sol.dark
fi

# Fix locale
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
# }}}

# Plugins config & ENV {{{
# zsh-completions. https://github.com/zsh-users/zsh-completions/
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240"   # fg=#707a8c,bg=cyan,bold,underline"

# zsh-history-substring-search. https://github.com/zsh-users/zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# nnn - https://github.com/jarun/nnn
export NNN_PLUG='f:fzcd;o:fzopen;z:fzz;d:diffs;t:treeview;v:preview-tui;h:fzhist;c:chksum;m:mediainf;z:fzz;k:pskill;n:nuke'
export NNN_OPTS='acdEHFrxQU'
export NNN_OPENER='nuke'
if [[ $HOST_NAME == 'hqsvr' ]]; then
  export NNN_BMS='d:~/dotfiles;x:/HQPOOL/Videos/xXx;v:/HQPOOL/Videos;c:/HQPOOL/DATA/Coding;T:/HQPOOL/DATA;p:/HQPOOL;D:/HQPOOL/Downloads'
elif [[ $HOST_NAME == 'HQ' ]]; then
  export NNN_BMS='d:~/dotfiles;D:/Volume/HOME/Downloads'
fi

# bat - https://github.com/sharkdp/bat
export BAT_THEME="Monokai Extended"
export BAT_STYLE="plain"
export BAT_PAGER="less -RS"

# enhancd - https://github.com/b4b4r07/enhancd
export ENHANCD_DISABLE_DOT=1
export ENHANCD_DISABLE_HYPHEN=0
export ENHANCD_HYPHEN_ARG=':'

# https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2
if [ -d $HOME/.fzf ]; then
  # PREVIEW WINDOW OPTIONS down:3:hidden:wrap --bind '?:toggle-preview'
fi

# FIX the blinding green on green directory listing on external drive.
# Read more https://unix.stackexchange.com/questions/94498/what-causes-this-green-background-in-ls-output
if [[ -f ~/.dircolors ]]; then
  eval $(dircolors -b ~/.dircolors)
elif [[ -f /etc/DIR_COLORS ]]; then
  eval $(dircolors -b /etc/DIR_COLORS)
fi
# }}}

# Update $PATH (platform *nix)) {{{
hash npm      2>/dev/null && export NPM_CONFIG_PREFIX=$HOME/.npm-global   # npm -g install location
hash npm      2>/dev/null && export PATH=$HOME/.npm-global/bin:$PATH      # npm global binary path
[[ -f ~/.local/bin/pip ]] && export PATH=$HOME/.local/bin:$PATH           # pip app binary path
hash cargo    2>/dev/null && export PATH=$HOME/.cargo/bin:$PATH           # rust cargo binary path
hash composer 2>/dev/null && export PATH=$HOME/.composer/vendor/bin:$PATH # rust cargo binary path
hash snap     2>/dev/null && export PATH=/snap/bin:$PATH                  # snap binary path
export PATH=$PATH:$DENO_INSTALL/bin                                       # deno binary path
export PATH=$DOTFILES_HOME/bin:$PATH
# }}}

# Extra sources {{{
[[ -x rustup ]] && source $HOME/.cargo/env
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
[[ -d ~/.fzf ]] && source $DOTFILES_HOME/zsh/fzf.zsh
hash nnn 2> /dev/null && source $DOTFILES_HOME/nnn/quitcd.zsh
hash hunter 2> /dev/null && source $HOME/.config/hunter/hunter_cd.sh

source $DOTFILES_HOME/zsh/default.zsh # my aliases
source $DOTFILES_HOME/zsh/aliases.zsh # my aliases
source $HOME/.secret                  # don't commit this file
typeset -U PATH                       # remove dups from $PATH
# }}}

# alias luamake=/Users/kuntau/coding/forks/lua-language-server/3rd/luamake/luamake
