[mgr]
ratio          = [ 1, 3, 5 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true

[preview]
tab_size        = 5
max_width       = 1000
max_height      = 1000
cache_dir       = ""
image_filter    = "lanczos3"
image_quality   = 90
sixel_fraction  = 15

[opener]
edit = [
    { run = '${EDITOR:-vi} "$@"', block = true, for = "unix" },
]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
    { mime = "text/*",  use = "edit" },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
    { mime = "image/*", use = "open" },
]

[[plugin.prepend_previewers]]
url = "*.md"
run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
mime = "video/*"
run = 'faster-piper -- mediainfo "$1"'

[[plugin.prepend_previewers]]
url = "*/"
run = 'piper -- eza -TL=1 --color=always --icons=always --group-directories-first --no-quotes "$1"'

[[plugin.prepend_previewers]]
mime = "application/pdf"
run = 'faster-piper -- mediainfo "$1"'

[[plugin.prepend_previewers]]
mime = "application/sqlite3"
run  = 'faster-piper -- sqlite3 "$1" ".schema --indent"'

[[plugin.prepend_previewers]]
mime = "application/x-tar"
run  = 'faster-piper -- tar -tf "$1"'

[[plugin.prepend_previewers]]
mime = "application/x-zip"
run  = 'faster-piper -- 7zz l "$1"'

[[plugin.prepend_previewers]]
mime = "text/*"
run = 'faster-piper -- $PAGER "$1"'

# [[plugin.prepend_previewers]]
# url = "*"
# run = 'faster-piper -- file "$1"'
