# Neovide configs reference: https://neovide.dev/config-file.html
# Not sure which take priority, config file or inside neovim configs

fork = false
frame = "full"
idle = true
maximized = false
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = true
srgb = true
tabs = false
theme = "auto"
title-hidden = true
vsync = true
wsl = false

# [font]
# normal = [ "Maple Mono", "Cascadia Code" ] # Will use the bundled Fira Code Nerd Font by default
# style = "Medium"
# size = 13.0

[font]
normal = [ "Cascadia Code", "Operator Mono" ] # Will use the bundled Fira Code Nerd Font by default
style = "Regular"
size = 13.0

# [[font.normal]]
# family = "MonoLisa"
# weight = "Normal"
# style = "Normal"

[font.features]
"Maple Mono" = ["+calt", "+liga", "+ss01", "+ss02", "+ss03"]
"MonoLisa" = [ "+ss01", "+ss07", "+ss11", "-calt", "+ss09", "+ss02", "+ss14" ]
"Cascadia Code" = [ "+ss01", "+ss02", "+ss03", "+calt", "+ss19", "+ss20" ]
