# Neovide configs reference: https://neovide.dev/config-file.html
# Not sure which take priority, config file or inside neovim configs
[font]
    normal = [] # Will use the bundled Fira Code Nerd Font by default
    size = 13.0

fork = false
frame = "full"
idle = true
maximized = false
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false
